### PR TITLE
Include a theme toggler in the navbar

### PR DESCRIPTION
**Pull request by Young-Einstein10**
This PR contains an implementation for a button to toggle the theme in the Navbar.

Resolves [Issue 461](https://github.com/boxyhq/saas-starter-kit/issues/461)

## Screenshots

Screenshot 2023-09-06 at 23 44 17

Screenshot 2023-09-06 at 23 45 04

### CODE REVIEW

**Comment by devkiran** [comment]
@Young-Einstein10 is this PR ready to review?

**Comment by Young-Einstein10** [comment]
Yes, it is.

**Comment by devkiran** [comment]
LGTM

**Comment by Young-Einstein10** [comment]
I'm glad I could be of help💪

**Comment by KazeroG** [comment]
@Young-Einstein10 The toggle doesn't show up when connected into the dashboard

**Pull request merged**
