### PR TITLE
docs: Update README with detailed technology descriptions

### PR DESCRIPTION
**Pull request by Musyonchez**
Update README with Detailed Technology Descriptions

### CODE REVIEW

**Review by ukrocks007 — APPROVED** [review]

**Comment by ukrocks007** [comment]
Formatting needs to be applied
`npm run format`

**Review by ukrocks007 — CHANGES_REQUESTED** [review]
Formatting needs to be applied
`npm run format`

**Comment by Musyonchez** [comment]
I dont know why but the commits for this PR are for "refactor(env): simplify ternary statement for dsync feature flag #1183" and the actual onces have been closed in "docs: Update features list in README #1174" .  @ukrocks007  Do i create another PR or just update this one?

**Comment by ukrocks007** [comment]
> I dont know why but the commits for this PR are for "refactor(env): simplify ternary statement for dsync feature flag #1183" and the actual onces have been closed in "docs: Update features list in README #1174" .  @ukrocks007  Do i create another PR or just update this one?
> 
> 

You can update this PR itself

**Comment by Musyonchez** [comment]
@ukrocks007 Done Please Check.

**Review by ukrocks007 — APPROVED** [review]

**Comment by deepakprabhakara** [comment]
Thanks @Musyonchez.

**Pull request merged**
