### PR TITLE
 Add a 'Deploy to DigitalOcean' Button

### PR DESCRIPTION
**Pull request by Saptarshee94**
This Pull request adds the `Deploy to DigitalOcean` button in the Readme.md of the project.

### CODE REVIEW

**Comment by Saptarshee94** [comment]
> Can you resolve the conflict in the README.md? Does DO allow making the env variable optional?

1. Conflict resolved.
2. As far, there is no reference for `required` like option in their document [Add Deploy to DigitalOcean button](https://docs.digitalocean.com/products/app-platform/how-to/add-deploy-do-button/) but it is possible to bind environment variables. I am not sure how it's handled from DO's side while deploying, as I am unable to test the deployment here.

**Comment by devkiran** [comment]
Thanks for the PR. I'll test it tomorrow.

**Comment by devkiran** [comment]
I couldn't test the button, has some issues with DO. Need to review in details.

**Review by devkiran — APPROVED** [review]

**Comment by devkiran** [comment]
Closes #11

**Pull request merged**
