### PR TITLE
Fix: UI issue

### PR DESCRIPTION
**Pull request by rohitmondal03**
Fix: #636 
Fixed UI issues

### CODE REVIEW

**Comment by rohitmondal03** [comment]
@devkiran why the checks are failing? I have synced my repo and also updated my local copy in PC. On running `npm run format` it is showing 205 files changed.

**Comment by devkiran** [comment]
@rohitmondal03 Can you please pull the changes from main and fix the conflict?

**Comment by devkiran** [comment]
@rohitmondal03 is this still relevant? I think it is already covered in a different PR.

**Comment by rohitmondal03** [comment]
> @rohitmondal03 is this still relevant? I think it is already covered in a different PR.

Yess, I guess it has been already covered in different PR.

**Comment by devkiran** [comment]
Thanks @rohitmondal03

**Pull request closed without merging**
