### PR TITLE
fix untransltIdentify Untranslated Text and Include it in locales/en/…

### PR DESCRIPTION
**Pull request by belkhoujaons**
fix untransltIdentify Untranslated Text and Include it in locales/en/…

### CODE REVIEW

**Review by deepakprabhakara — CHANGES_REQUESTED** [review]
thank you @belkhoujaons . Please use all lowercase for the string identifiers in common.json

**Comment by belkhoujaons** [comment]
done, please review again

**Comment by devkiran** [comment]
@belkhoujaons I tested one email template, but I'm getting this error:

```
Cannot read properties of null (reading 'useContext')
```

Can you please test all email templates and make sure they work?

**Comment by devkiran** [comment]
@belkhoujaons Tested with main branch, couldn't reproduce this issue so this happens with your branch. This could be because of `useTranslation` within the email template. Please check react.email support this hook/translation.

**Comment by belkhoujaons** [comment]
> @belkhoujaons Tested with main branch, couldn't reproduce this issue so this happens with your branch. This could be because of `useTranslation` within the email template. Please check react.email support this hook/translation.

it should be fixed now

**Comment by deepakprabhakara** [comment]
@belkhoujaons One more small task, you'll need to run `npm run format` and check in the formatting changes so ci/cd passes.

**Comment by devkiran** [comment]
@belkhoujaons The issue is not resolved. I'm still getting the same error. I would appreciate it if you could test it locally from your side.

**Comment by belkhoujaons** [comment]
> @belkhoujaons The issue is not resolved. I'm still getting the same error. I would appreciate it if you could test it locally from your side.

weirdly enough, when I deleted .next folder and run "npm run dev" the issue vanished, can you please try it and see what happens ?

**Comment by belkhoujaons** [comment]
@devkiran & @deepakprabhakara we can"t for now use the useTranslation hook inside email templates since they're not being wrapped by the i18n provider, so I'll close this PR and submit another one where the changes are in normal React components
but it was nice building the project with docker and exploring the prisma ! nice work I like it

**Pull request closed without merging**
