### PR TITLE
Added meta tags

### PR DESCRIPTION
**Pull request by rohitmondal03**
Fix: #565 
Added meta tags in all pages of website

### CODE REVIEW

**Comment by deepakprabhakara** [comment]
@rohitmondal03 We have added prettier format to standardise formatting across the source files. Could you please merge main and then run `npm run format`.

**Comment by rohitmondal03** [comment]
> @rohitmondal03 We have added prettier format to standardise formatting across the source files. Could you please merge main and then run `npm run format`.

Should I run `npm run format` and then merge it ??

**Comment by rohitmondal03** [comment]
@deepakprabhakara I have ran `npm run format`, but it is changing 203 files of the repo
.

**Comment by devkiran** [comment]
@rohitmondal03 Can you please pull the changes from main and fix the conflicts?

**Comment by rohitmondal03** [comment]
> @rohitmondal03 Can you please pull the changes from main and fix the conflicts?

Ok I'll do that

**Comment by rohitmondal03** [comment]
Should I only have to add title tag as shown in conflicts ?? @devkiran

**Comment by rohitmondal03** [comment]
@devkiran will I only have to add `<title>t("title here")</title>` in the components ?

**Comment by devkiran** [comment]
@rohitmondal03 Yes.

**Pull request closed without merging**
