### PR TITLE
added missing dependencies to useEffect React Hook

### PR DESCRIPTION
**Pull request by Andrewx24**
warning  React Hook useEffect has missing dependencies: 'jacksonEnv.externalUrl' and 'jacksonEnv.selfHosted'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

### CODE REVIEW

**Review by niwsa — CHANGES_REQUESTED** [review]
@Andrewx24 Please run `npm run format` to fix the formatting errors.

**Comment by Andrewx24** [comment]
> @Andrewx24 Please run `npm run format` to fix the formatting errors.
ran npm run format` to fix the formatting errors.

**Review by niwsa — APPROVED** [review]

**Comment by deepakprabhakara** [comment]
Thanks @Andrewx24

**Comment by Andrewx24** [comment]
> Thanks @Andrewx24

Your welcome

**Pull request merged**
