### PR TITLE
fix: darkmode breaks on some places

### PR DESCRIPTION
**Pull request by saqibtanveer786**
This PR fixes the issue #1011 

The dark mode was not working on some places like in dropdown, navigation etc. This PR tends to fix that.

### CODE REVIEW

**Comment by deepakprabhakara** [comment]
Thanks @saqibtanveer786, we'll review this soon.

**Comment by devkiran** [comment]
@saqibtanveer786 Can you please take a look at sidebar items?

**Review by devkiran — CHANGES_REQUESTED** [review]
Please check my comment. There is an issue with sidebar item.

**Comment by saqibtanveer786** [comment]
now its working fine 
Screenshot from 2024-03-11 11-06-58

i don't know why text-gray-100 not working but text-white got worked

**Review by alexindris — APPROVED** [review]

**Review by deepakprabhakara — APPROVED** [review]

**Comment by deepakprabhakara** [comment]
Many thanks @saqibtanveer786, LGTM.

**Pull request merged**
