### PR TITLE
fix/authenticated-user-routed-to-dashboard-route

### PR DESCRIPTION
**Pull request by rohitmondal03**
Fix: #535 
Fixed the problem, where the authenticated user will not be able to head in landing page.

### CODE REVIEW

**Comment by deepakprabhakara** [comment]
@rohitmondal03 We will review shortly but could you please apply the prettier config we have in the root folder on this file please. The formatting change is larger than the actual change and hard to notice the real diff.

**Comment by rohitmondal03** [comment]
Should I change the tab size ??

**Comment by deepakprabhakara** [comment]
Our prettier config is here - https://github.com/boxyhq/saas-starter-kit/blob/main/.prettierrc

**Comment by shartrooper** [comment]
Can you look into this ? 
image

**Comment by rohitmondal03** [comment]
@shartrooper  I'm not getting this issue. Can you tell hiw you got the issue ?

**Comment by shartrooper** [comment]
> @shartrooper I'm not getting this issue. Can you tell hiw you got the issue ?

I cloned your fork, installed dependencies, and run the app with "npm run dev" command. This happens just after logging in.

**Pull request closed without merging**
